
- hosts: all
  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: safe
      become: true

    - name: Install packages via apt
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - git
        - mongodb
        - nginx
      become: true

    - name: Create /data/db folder for Mongo
      file: path=/data/db state=directory
      become: true

    - name: Pull Node
      get_url: 
        url: https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz
        dest: /home/vagrant

    - name: Extract Node
      unarchive: src=/home/vagrant/node-v6.9.1-linux-x64.tar.xz dest=/home/vagrant remote_src=yes

    - name: Move Node to bin
      copy: src=/home/vagrant/node-v6.9.1-linux-x64/bin/node dest=/usr/local/bin remote_src=yes
      become: true

    - name: Chown node and make executable
      file: path=/usr/local/bin/node owner=vagrant mode="u=rwx,g=rwx,o=rx"
      become: true

    - name: Chown /usr/local/bin
      file: path=/usr/local/bin owner=vagrant state=directory recurse=yes
      become: true

    - name: Chown /usr/local/lib
      file: path=/usr/local/lib owner=vagrant state=directory recurse=yes
      become: true

    - name: Create mongodb user
      command: mongo cla_assistant --eval "db.addUser({user"{{":"}}" 'cla_assistant', pwd"{{":"}}" 'cla_assistant', roles"{{":"}}"[]})"

    - name: Install NPM
      shell: ./npm install -g npm@latest
      args:
        chdir: /home/vagrant/node-v6.9.1-linux-x64/bin

    - name: clone git repo
      git: repo=https://github.com/cla-assistant/cla-assistant.git dest=/home/vagrant/cla-assistant clone=yes

    - name: NPM install
      npm: path=/home/vagrant/cla-assistant
      register: result

    - name: Add NGINX configuration for Cla-assistant
      copy: src=files/cla.conf dest=/etc/nginx/conf.d/cla.conf
      become: true

    - name: Reload Nginx
      command: nginx -s reload
      become: true

    - name: Copy .env file
      copy: src=files/cla-assistant.env dest=/home/vagrant/cla-assistant/.env

    - name: Install forever
      npm: name=forever global=yes state=present

    - name: Check list of Node.js apps running
      command: forever list
      register: forever_list
      changed_when: false

    - name: build with grunt
      shell: ./node_modules/grunt-cli/bin/grunt build
      when: result|succeeded
      args:
        chdir: /home/vagrant/cla-assistant

    - name: Source .env and start forever
      shell: . ./.env && forever start app.js
      args:
        chdir: /home/vagrant/cla-assistant
