---

- hosts: all
  sudo: true
  tasks:
    - name: add mongodb key
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
      become: true
    - name: create source list file for mongodb
      shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    - name: Add node files
      shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - name: update
      apt:
        update_cache: yes
    - name: upgrade
      apt:
        upgrade: yes
    - name: install mongodb
      apt:
        name: mongodb-org
        state: present
    - name: install node
      apt:
        name: nodejs
        state: present
    - name: install build essential
      apt:
        name: build-essential
        state: present
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: add nginx server file
      shell: src=cla.conf dest=/etc/nginx/conf.d/cla.conf
    - name: reload nginx
      shell: sudo nginx -s reload 
    - name: install git
      apt:
        name: git
    - name: clone git repo
      shell: git clone https://github.com/cla-assistant/cla-assistant.git
    - name: copy .env file
      copy: src=.env dest=/home/vagrant/cla-assistant/.env
    - name: change directory and npm install
      shell: cd /home/vagrant/cla-assistant && sudo npm install
    - name: build with grunt
      shell: cd /home/vagrant/cla-assistant && /home/vagrant/cla-assistant/node_modules/grunt-cli/bin/grunt build
    - name: source .env
      shell: . /home/vagrant/cla-assistant/.env
    - name: create cla autostart file
      copy: src=cla.service dest=/etc/systemd/system/cla.service
    - name: REBOOT
      shell: sudo shutdown -r now
