
- hosts: all
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install packages via apt
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - git
        - mongodb
        - nginx
        - nodejs

    # NOTE! Use this instead, http://docs.ansible.com/ansible/git_module.html
    # - name: clone git repo
    #   shell: git clone https://github.com/cla-assistant/cla-assistant.git

    # NOTE! Use this instead, http://docs.ansible.com/ansible/npm_module.html
    # - name: change directory and npm install
    #   shell: sudo npm install
    #   args:
    #     chdir: /home/vagrant/cla-assistant

    # Note! This should only be run **IF** we just installed the node_modules.
    # - name: build with grunt
    #   shell: /home/vagrant/cla-assistant/node_modules/grunt-cli/bin/grunt build
    #   args:
    #     chdir: /home/vagrant/cla-assistant

    - name: Add NGINX configuration for CLA service
      copy: src=cla.conf dest=/etc/nginx/conf.d/cla.conf

    # Note! Use this instead, https://docs.ansible.com/ansible/systemd_module.html
    # - name: reload nginx
    #   shell: sudo nginx -s reload

    # - name: Copy .env file
    #   copy: src=cla-assistant.env dest=/home/vagrant/cla-assistant/.env

    - name: Create CLA autostart file
      copy: src=cla.service dest=/etc/systemd/system/cla.service

